[project]
name = "swn-sector-generator"
dynamic = ["version"]
description = "Advanced sector generator for the Stars Without Number TTRPG"
readme = "README.md"

requires-python = ">=3.14"

dependencies = [
    "PyYAML==6.0.3",
]

[project.optional-dependencies]
dev = [
    "git-cliff==2.13.1",
    "jsonschema==4.26.0",
    "mypy==1.18.2",
    "pre-commit==4.3.0",
    "pymarkdownlnt==0.9.39",
    "pytest==9.0.3",
    "pytest-cov==7.0.0",
    "ruff==0.13.0",
    "setuptools-scm==10.2.1",
]

[build-system]
requires = ["setuptools>=80", "setuptools-scm>=10"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = [
    "--import-mode=importlib",
    "--cov=src/swn_sector_generator",
    "--cov-report=term-missing",
    "--cov-fail-under=80",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools_scm]
version_file = "src/swn_sector_generator/_version.py"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
swn_sector_generator = [
    "resources/**/*",
]